config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from rest_framework import routers
from api.views import GaragemList, GerarGaragens, PessoaComVeiculosList, PessoaList, PessoaSemVeiculosList, VeiculoList

from rest_framework import routers

admin.autodiscover()
router = routers.DefaultRouter()
router.register("garagens", GaragemList)
router.register("pessoas", PessoaList)
router.register("veiculos", VeiculoList)
router.register("pessoas-com-veiculos", PessoaComVeiculosList, basename="pessoa-com-veiculos")
router.register("pessoas-sem-veiculos", PessoaSemVeiculosList, basename="pessoa-sem-veiculos")
router.register("gerar-garagens", GerarGaragens, basename="gerar-garagens")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('conta/', include("django.contrib.auth.urls")),
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path('api/', include(router.urls)),
]

for app_name in settings.LOCAL_APPS:
    urlpatterns += [
        path(f"{app_name}/", include(f"{app_name}.urls", namespace=str(app_name))),
    ]

garagem/urls.py
from garagem import views_veiculo
from django.urls import path

from . import views, views_veiculo

app_name = 'garagem'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:veiculo_id>/vincular', views.create, name='create'),
    path('<int:veiculo_id>/desvincular', views.remove, name='desvincular'),    
    path('<int:id>/update', views.update, name='update'),
    path('<int:id>/delete', views.delete, name='delete'),

    path('gerar', views.auto_create, name='auto_create'),

    path('veiculos', views_veiculo.index, name='index_veiculos'),
    path('veiculos/cadastrar', views_veiculo.create, name='create_veiculo'),
    path('veiculos/<int:id>/update', views_veiculo.update, name='update_veiculo'),
    path('veiculos/<int:id>/delete', views_veiculo.delete, name='delete_veiculo'),
]

garagem/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Veiculo(models.Model):
    tipo_veiculo = [
        (0, "Carro"),
        (1, "Moto")
    ]
    
    cor = models.CharField("Cor", max_length=50, blank=True, null=True)
    ano = models.IntegerField("Ano", blank=True, null=True)
    modelo = models.CharField("Modelo", max_length=50, blank=True, null=True)
    tipo = models.IntegerField("Tipo", choices=tipo_veiculo, default=0)

    class Meta:
        verbose_name = "Veiculo"
        verbose_name_plural = "Veiculos"

    def __str__(self):
        if self.tipo == 0:
            result = f"Carro, {self.ano}, {self.cor}"
        else:
            result = f"Moto, {self.ano}, {self.modelo}"

        return result


class Garagem(models.Model):
    pessoa = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)
    veiculo = models.ForeignKey(Veiculo, blank=True, null=True, on_delete=models.PROTECT)
    telefone = models.CharField('Telefone', max_length=15)
    email = models.EmailField("E-mail", max_length=100)

    class Meta:
        verbose_name = "Garagem"
        verbose_name_plural = "Garagens"
        constraints = [
            models.UniqueConstraint(fields=['pessoa', 'veiculo'], name='Veiculo único para pessoa')
        ]
        ordering = ['pessoa']

    def __str__(self):
        return f"{self.pessoa} - {self.veiculo} - {self.telefone} - {self.email}"

garagem/forms.py
from django import forms
from .models import Garagem, Veiculo

class GaragemModelForm(forms.ModelForm):
    class Meta:
        model = Garagem
        fields = "__all__"


class VeiculoModelForm(forms.ModelForm):
    class Meta:
        model = Veiculo
        fields = "__all__"

garagem/views.py
from garagem.models import Veiculo
import os 
from django.http import request
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from rest_framework import viewsets

from pessoa.models import Pessoa
from .forms import GaragemModelForm, Garagem
# from .serializer import PessoaSerializer

app_name = 'garagem'

pages = {
    'index.html': os.path.join(app_name, "index.html"),
    f'{app_name}_form.html': os.path.join(app_name, f"{app_name}_form.html"),
    f'{app_name}_delete.html': os.path.join(app_name, f"{app_name}_delete.html"),
    f'{app_name}_list_veiculos.html': os.path.join(app_name, f"{app_name}_list_veiculos.html")
}

context = {'titulo': 'Garagens'}

def index(request):
    
    if (request.user.is_staff):
        garagens = Garagem.objects.all()
        context['garagens'] = garagens        
        return render(request, pages['index.html'], context)
    else:
        garagem = Garagem.objects.filter(pessoa=request.user.id)
        
        if not garagem.exists():
            garagem = Garagem(pessoa=request.user, telefone=request.user.telefone, email=request.user.email)
            garagem.save()

        garagens = Garagem.objects.filter(pessoa=request.user.id)

        # Veiculos vinculados
        veiculos_vinculados = []
        for garagem in garagens:
            veiculos_vinculados.append(garagem.veiculo)
        
        for v in veiculos_vinculados:
            if not v:
                veiculos_vinculados.remove(v)

        print(request.user)
        print(veiculos_vinculados)
        # Veiculos não vinculados
        veiculos_nao_vinculados = []
        veiculos = Veiculo.objects.all()
        for veiculo in veiculos:
            if veiculo not in veiculos_vinculados:
                veiculos_nao_vinculados.append(veiculo)

        context['garagem'] = garagem        
        context['veiculos_vinculados'] = veiculos_vinculados
        context['veiculos_nao_vinculados'] = veiculos_nao_vinculados


        return render(request, pages[f'{app_name}_list_veiculos.html'], context)


def create(request, veiculo_id):

    veiculo = Veiculo.objects.get(id=veiculo_id)

    garagem = Garagem(pessoa=request.user, veiculo=veiculo, telefone=request.user.telefone, email=request.user.email)
    garagem.save()

    return redirect('garagem:index')


def remove(request, veiculo_id):
    
    garagem = Garagem.objects.filter(veiculo=veiculo_id, pessoa=request.user.id)
    garagem.delete()
    return redirect('garagem:index')


def update(request, id):
    garagem = get_object_or_404(Garagem, id=id)

    if request.user.is_authenticated:
        form = GaragemModelForm(request.POST or None, instance=garagem)

    context['form'] = form


    if str(request.method) == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, 'Garagem atualizada com sucesso.')

            return redirect('garagem:index')
        else:
            messages.error(request, 'Não foi possível atualizar o cadastro.')

    return render(request, pages[f'{app_name}_form.html'], context)


def delete(request, id):
    garagem = get_object_or_404(Garagem, id=id)
    context['garagem'] = garagem

    if str(request.method) == 'POST':
        garagem.delete()
        return redirect('garagem:index')

    return render(request, pages[f'{app_name}_delete.html'], context)
    

def auto_create(request):

    pessoas = Pessoa.objects.all()

    for p in pessoas:

        exist = Garagem.objects.filter(pessoa=p.id).exists()
        if not exist:
            garagem = Garagem(pessoa=p, telefone=p.telefone, email=p.email)
            garagem.save()
    
    messages.success(request, "Garagens criadas com sucesso.")
    return redirect('garagem:index')
        

garagem/templates/veiculo/header.html
<div class="page-header text-center p-4 row justify-content-center">
    <div class="col-10">
    <h2><a href="{% url 'garagem:index_veiculos' %}">
            {{ titulo }}
    </a></h2>
    </div>
    <div class="col-2">
        <a href="{% url 'index' %}" class="btn btn-outline-dark">Início</a>
        <a class="btn btn-danger" href="{% url 'logout' %}">Logout</a>
    </div>
</div>

garagem/templates/veiculo/index.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block titulo %}
    {{ titulo }}
{% endblock titulo %} 

{% block content %}
    {% include "veiculo/header.html" %}

    <div class="row">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Tipo</th>
                    <th scope="col">Ano</th>
                    <th scope="col">Cor</th>
                    <th scope="col">Modelo</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for veiculo in veiculos %}
                <tr>
                    <td>
                        {% if veiculo.tipo == 0 %}
                            Carro
                        {% else %}
                            Moto
                        {% endif %}
                    </td>
                    <td>{{ veiculo.ano }}</td>
                    <td>{{ veiculo.cor|default_if_none:"-" }}</td>
                    <td>{{ veiculo.modelo|default_if_none:"-" }}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'garagem:update_veiculo' veiculo.id %}">Editar</a>
                        <a class="btn btn-danger" href="{% url 'garagem:delete_veiculo' veiculo.id %}">Excluir</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="row">
        <div class="col-lg-2">
            <a href="{% url 'garagem:create_veiculo' %}" class="btn btn-primary">Novo</a>
        </div>
    </div>
    {% if messages %}
        {% for message in messages %}
            <div class="row">
                <div class="alert alert-{{ message.tags }} alert-dismissible m-auto" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock content %}

garagem/templates/veiculo/veiculo_delete.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
{% include "veiculo/header.html" %}
<div class="row">
    <div class="col-5 align-content-center p-4 border border-dark text-center m-auto shadow rounded">
    <form method="POST">
        {% csrf_token %}
        <p>Tem certeza que deseja excluir o veículo <br> "{{ veiculo }}"?</p>
        {% buttons %}
            <button type="submit" class="btn btn-danger">Confirmar</button>
            <a class="btn btn-warning" href="{% url 'garagem:index_veiculos' %}">Cancelar</a>
        {% endbuttons %}
    </form>
    </div>
</div>
{% endblock content %}

garagem/templates/veiculo/veiculo_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block titulo %}
    {{ titulo }}
{% endblock titulo %} 

{% block content %}

{% include "veiculo/header.html" %}

<div class="text-left">
    <form method="POST" class="form" autocomplete="off">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button type="submit" class="btn btn-primary">Salvar</button>
            <a href="{% url 'garagem:index_veiculos' %}" class="btn btn-warning">Cancelar</a>
        {% endbuttons %}        
    </form>
</div>

  
{% endblock content %}