config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from rest_framework import routers
from api.views import GaragemList, GerarGaragens, PessoaComVeiculosList, PessoaList, PessoaSemVeiculosList, VeiculoList

from rest_framework import routers

admin.autodiscover()
router = routers.DefaultRouter()
router.register("garagens", GaragemList)
router.register("pessoas", PessoaList)
router.register("veiculos", VeiculoList)
router.register("pessoas-com-veiculos", PessoaComVeiculosList, basename="pessoa-com-veiculos")
router.register("pessoas-sem-veiculos", PessoaSemVeiculosList, basename="pessoa-sem-veiculos")
router.register("gerar-garagens", GerarGaragens, basename="gerar-garagens")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('conta/', include("django.contrib.auth.urls")),
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path('api/', include(router.urls)),
]

for app_name in settings.LOCAL_APPS:
    urlpatterns += [
        path(f"{app_name}/", include(f"{app_name}.urls", namespace=str(app_name))),
    ]

pessoa/urls.py
from django.urls import path

from . import views

app_name = 'pessoa'

urlpatterns = [
    path('', views.index_pessoa, name='index'),
    path('cadastrar', views.create_pessoa, name='create'),
    path('<int:id>/update', views.update_pessoa, name='update'),
    path('<int:id>/delete', views.delete_pessoa, name='delete')
]

pessoa/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


class UsuarioManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("O e-mail é obrigatório")
        
        email = self.normalize_email(email)
        user = self.model(email=email, username=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError("Superuser precisa ter is_superuser=True")

        if extra_fields.get('is_staff') is not True:
            raise ValueError("Superuser precisa ter is_staff=True")

        return self._create_user(email, password, **extra_fields)


class Pessoa(AbstractUser):

    tipo_pessoa = (
        (False, "Consumidor"),
        (True, "Administrador")
    )

    nome = models.CharField('Nome', max_length=100)
    telefone = models.CharField('Telefone', max_length=15)
    email = models.EmailField("E-mail", max_length=100, unique=True)
    is_staff = models.BooleanField("Administrador", default=True, choices=tipo_pessoa)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nome', 'telefone']


    class Meta:
        verbose_name = "Pessoa"
        verbose_name_plural = "Pessoas"
        
    def __str__(self):
        return self.nome

    objects = UsuarioManager()

pessoa/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from .models import Pessoa


class PessoaModelFormConsumidor(forms.ModelForm):
    class Meta:
        model = Pessoa
        fields = ['nome', 'telefone', 'email']


class PessoaModelFormAdmin(forms.ModelForm):
    class Meta:
        model = Pessoa
        fields = ['nome', 'telefone', 'email', 'is_staff']



class PessoaCreateForm(UserCreationForm):
    class Meta:
        model = Pessoa
        fields = ('nome', 'telefone', 'username', 'is_staff')
        labels = {'username': 'Username/Email' }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.email = self.cleaned_data['username']

        if commit:
            user.save()

        return user

class PessoaChangeForm(UserChangeForm):
    class Meta:
        models = Pessoa
        fields = ('nome', 'telefone', 'is_staff')

pessoa/views.py
import os 
from django.http import request
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from rest_framework import viewsets

from .models import Pessoa
from .forms import PessoaChangeForm, PessoaCreateForm, PessoaModelFormAdmin, PessoaModelFormConsumidor
from .apps import PessoaConfig

app_name = "pessoa"

pages = {
    'index.html': os.path.join(app_name, "index.html"),
    f'{app_name}_form.html': os.path.join(app_name, f"{app_name}_form.html"),
    f'{app_name}_delete.html': os.path.join(app_name, f"{app_name}_delete.html")
}


context = {'titulo': 'Pessoas'}

def index_pessoa(request):
    
    if (request.user.is_staff):
        pessoas = Pessoa.objects.all()

        context['pessoas'] = pessoas
        
        return render(request, pages['index.html'], context)

    return redirect('index')

def create_pessoa(request):

    if request.user.is_staff:
        form = PessoaCreateForm(request.POST or None)
    else:
        form = PessoaModelFormConsumidor(request.POST or None)
    
    context['form'] = form
    if str(request.method) == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, 'Pessoa cadastrada com sucesso.')
            return redirect('pessoa:index')
        else:
            messages.error(request, 'Não foi possível realizar o cadastro.')

    return render(request, pages[f'{app_name}_form.html'], context)

def update_pessoa(request, id):
    pessoa = get_object_or_404(Pessoa, id=id)

    if not request.user.is_staff:
        form = PessoaModelFormConsumidor(request.POST or None, instance=pessoa)
    else:
        form = PessoaModelFormAdmin(request.POST or None, instance=pessoa)

    context['form'] = form

    if str(request.method) == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, 'Pessoa atualizada com sucesso.')

            return redirect('pessoa:index')
        else:
            messages.error(request, 'Não foi possível atualizar o cadastro.')

    return render(request, pages[f'{app_name}_form.html'], context)


def delete_pessoa(request, id):
    pessoa = get_object_or_404(Pessoa, id=id)
    context['pessoa'] = pessoa

    if str(request.method) == 'POST':
        try:
            pessoa.delete()
            return redirect('pessoa:index')
        except:
            messages.error(request, "Não é possível excluir a pessoa, pois ela possui garagens vinculadas.")
            return redirect(pages['index.html'], context)

    return render(request, pages[f'{app_name}_delete.html'], context)

pessoa/templates/pessoa/header.html
<div class="page-header text-center p-4 row justify-content-center">
    <div class="col-10">
    <h2><a href="{% url 'pessoa:index' %}">
            {{ titulo }}
    </a></h2>
    </div>
    <div class="col-2">
        <a href="{% url 'index' %}" class="btn btn-outline-dark">Início</a>
        <a class="btn btn-danger" href="{% url 'logout' %}">Logout</a>
    </div>
</div>

pessoa/templates/pessoa/index.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
{% include "pessoa/header.html" %}
<div class="row">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Telefone</th>
                <th scope="col">Email</th>
                <th scope="col">Tipo</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for pessoa in pessoas %}
            <tr>
                <td>{{ pessoa.nome }}</td>
                <td>{{ pessoa.telefone }}</td>
                <td>{{ pessoa.email }}</td>
                <td>
                    {% if pessoa.is_staff %}
                        Administrador
                    {% else %}
                        Consumidor
                    {% endif %}
                </td>
                <td>
                    <a class="btn btn-primary" href="{% url 'pessoa:update' pessoa.id %}">Editar</a>
                    <a class="btn btn-danger" href="{% url 'pessoa:delete' pessoa.id %}">Excluir</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="row">
    <div class="col-lg-2">
        <a href="{% url 'pessoa:create' %}" class="btn btn-primary">Novo</a>
    </div>
</div>
{% if messages %}
<div class="row">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible m-auto" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
</div>
{% endfor %}
{% endif %}
{% endblock content %}

pessoa/templates/pessoa/pessoa_delete.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
{% include "pessoa/header.html" %}
<div class="row">
    <div class="col-5 align-content-center p-4 border border-dark text-center m-auto shadow rounded">
    <form method="POST">
        {% csrf_token %}
        <p>Tem certeza que deseja excluir a pessoa "{{ pessoa.nome }}"?</p>
        {% buttons %}
            <button type="submit" class="btn btn-danger">Confirmar</button>
            <a class="btn btn-warning" href="{% url 'pessoa:index' %}">Cancelar</a>
        {% endbuttons %}
    </form>
    </div>
</div>
{% endblock content %}

pessoa/templates/pessoa/pessoa_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
{% include "pessoa/header.html" %}

<div class="text-left">
<form method="POST" class="form" autocomplete="off">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
        <button type="submit" class="btn btn-primary">Salvar</button>
        <a href="{% url 'pessoa:index' %}" class="btn btn-warning">Cancelar</a>
    {% endbuttons %}        
</form>
</div>
  
{% endblock content %}