config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from rest_framework import routers
from api.views import GaragemList, GerarGaragens, PessoaComVeiculosList, PessoaList, PessoaSemVeiculosList, VeiculoList

from rest_framework import routers

admin.autodiscover()
router = routers.DefaultRouter()
router.register("garagens", GaragemList)
router.register("pessoas", PessoaList)
router.register("veiculos", VeiculoList)
router.register("pessoas-com-veiculos", PessoaComVeiculosList, basename="pessoa-com-veiculos")
router.register("pessoas-sem-veiculos", PessoaSemVeiculosList, basename="pessoa-sem-veiculos")
router.register("gerar-garagens", GerarGaragens, basename="gerar-garagens")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('conta/', include("django.contrib.auth.urls")),
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path('api/', include(router.urls)),
]

for app_name in settings.LOCAL_APPS:
    urlpatterns += [
        path(f"{app_name}/", include(f"{app_name}.urls", namespace=str(app_name))),
    ]

garagem/urls.py
from garagem import views_veiculo
from django.urls import path

from . import views, views_veiculo

app_name = 'garagem'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:veiculo_id>/vincular', views.create, name='create'),
    path('<int:veiculo_id>/desvincular', views.remove, name='desvincular'),    
    path('<int:id>/update', views.update, name='update'),
    path('<int:id>/delete', views.delete, name='delete'),

    path('gerar', views.auto_create, name='auto_create'),

    path('veiculos', views_veiculo.index, name='index_veiculos'),
    path('veiculos/cadastrar', views_veiculo.create, name='create_veiculo'),
    path('veiculos/<int:id>/update', views_veiculo.update, name='update_veiculo'),
    path('veiculos/<int:id>/delete', views_veiculo.delete, name='delete_veiculo'),
]

pessoa/urls.py
from django.urls import path

from . import views

app_name = 'pessoa'

urlpatterns = [
    path('', views.index_pessoa, name='index'),
    path('cadastrar', views.create_pessoa, name='create'),
    path('<int:id>/update', views.update_pessoa, name='update'),
    path('<int:id>/delete', views.delete_pessoa, name='delete')
]

templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% bootstrap_css %}
    <link href="https://getbootstrap.com/docs/5.0/examples/sign-in/signin.css" rel="stylesheet">
    <title>
        {% block titulo %}
        
        {% endblock titulo %}
    </title>
</head>
<body>    
    <div class="container justify-content-center">
        {% block content %}
        
        {% endblock content %}
    </div>
    
    {% bootstrap_javascript jquery='full' %}

</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="container text-center justify-content-center">
        <h1>Teste Franq OpenBank</h1>
        <br>
        {% if user.is_anonymous %}
            <a class="btn btn-primary" href="{% url 'login' %}">Login</a>  
        {% else %}
            <br>
            <h3>Bem-vindo(a) {{ user.nome }}</h3>
            <h5>Tipo: 
                {% if user.is_staff %}
                    Administrador
                {% else %}
                    Consumidor
                {% endif %}</h5>
            <br>
            
            <div class="btn-group" role="group" aria-label="Basic example">
                {% if user.is_staff %}
                    <a href="{% url 'pessoa:index' %}" class="btn btn-primary">Pessoas</a>
                {% else %}
                    <a href="{% url 'pessoa:update' user.id %}" class="btn btn-primary">Cadastro</a>
                {% endif %}
                    <a href="{% url 'garagem:index' %}" class="btn btn-primary">Garagens</a>
                    {% if user.is_staff %}
                    <a href="{% url 'garagem:index_veiculos' %}" class="btn btn-primary">Veículos</a>
                    {% endif %}
                {% if user.is_superuser %}
                    <a href="{% url 'admin:index' %}" class="btn btn-secondary">Administração</a>
                {% endif %}
                    <a class="btn btn-danger" href="{% url 'logout' %}">Logout</a>
            </div>
            
        {% endif %}
    </div>  
    {% if messages %}
    {% for message in messages %}
        <br>
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
        </div>
    {% endfor %}
    {% endif %}
{% endblock content %}